name: PaycheckPlanner
options:
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"

targets:
  PaycheckPlanner:
    type: application
    platform: iOS
    bundleId: com.example.PaycheckPlanner
    deploymentTarget: "17.0"
    sources:
      - path: PaycheckPlanner
        excludes: ["**/*.entitlements"]
    settings:
      base:
        INFOPLIST_FILE: PaycheckPlanner/Info.plist
        CODE_SIGN_ENTITLEMENTS: PaycheckPlanner/PaycheckPlanner.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ALWAYS_SEARCH_USER_PATHS: NO
        SWIFT_VERSION: "5.0"
        PRODUCT_NAME: PaycheckPlanner
        OTHER_LDFLAGS: ["-framework", "EventKit"]

  PaycheckPlannerWidgets:
    type: app-extension
    platform: iOS
    productName: PaycheckPlannerWidgets
    sources:
      - path: PaycheckPlannerWidgets
        excludes: ["**/*.entitlements"]
    settings:
      base:
        INFOPLIST_FILE: PaycheckPlannerWidgets/Info.plist
        CODE_SIGN_ENTITLEMENTS: PaycheckPlannerWidgets/PaycheckPlannerWidgets.entitlements
        ALWAYS_SEARCH_USER_PATHS: NO
        SWIFT_VERSION: "5.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.example.PaycheckPlanner.PaycheckPlannerWidgets
        OTHER_LDFLAGS: ["-framework", "WidgetKit", "-framework", "AppIntents"]

  PaycheckPlannerWatchApp:
    type: application.watchapp2
    platform: watchOS
    productName: PaycheckPlannerWatchApp
    sources:
      - path: PaycheckPlannerWatchApp
        optional: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.PaycheckPlanner.watchapp

  PaycheckPlannerWatchExtension:
    type: watchkit2-extension
    platform: watchOS
    productName: PaycheckPlannerWatchExtension
    sources:
      - path: PaycheckPlannerWatchExtension
        excludes: ["**/*.entitlements"]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.PaycheckPlanner.watchapp.watchkitextension
        CODE_SIGN_ENTITLEMENTS: PaycheckPlannerWatchExtension/PaycheckPlannerWatchExtension.entitlements
        SWIFT_VERSION: "5.0"

schemes:
  PaycheckPlanner:
    build:
      targets:
        PaycheckPlanner: all
        PaycheckPlannerWidgets: all
        PaycheckPlannerWatchApp: [build]
        PaycheckPlannerWatchExtension: [build]
    run:
      config: Debug
